# Generated by Django 2.1.5 on 2020-04-23 22:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=tinymce.models.HTMLField(default='Please enter your contents here!'),
        ),
    ]
