language: python

addons:
  apt:
    packages:
      - libenchant-dev

python:
  - "3.6"

before_install:
  - sudo apt-get install libxml2
  - sudo apt-get install libxmlsec1-dev
  - sudo apt-get install pkg-config
  - sudo apt-get install sshpass

install:
  - pip install tox-travis codecov

script:
  - tox

after_success:
  - codecov
  - ./deploy.sh $pa_pwd $pa_api_token

env:
  - TOXENV=py3
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=mypy
  - TOXENV=docs

notifications:
  slack: nycopen:xNh93jtqfsVnPM2gYAGVq8pc
