language: python

addons:
  apt:
    packages:
      - libenchant-dev
      - libxml2
      - libxmlsec1

python:
  - "3.6"

install:
  - pip install tox-travis codecov

script:
  - tox

after_success:
  - codecov

env:
  - TOXENV=py3
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=mypy
  - TOXENV=docs

notifications:
  slack: nycopen:xNh93jtqfsVnPM2gYAGVq8pc
